/*
 * Copyright (c) 2010, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.07.13 at 03:56:53 PM CEST
//
package org.glassfish.jersey.examples.jettison;

import java.util.Formatter;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for flightType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="flightType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="aircraft" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="flightId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flightType", propOrder = {
    "flightId",
    "company",
    "number",
    "aircraft"
})
public class FlightType {

    @XmlElement(required = true)
    protected String company;
    protected long number;
    @XmlElement(required = true)
    protected String aircraft;
    @XmlElement(required = true)
    protected String flightId;

    /**
     * Gets the value of the company property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the number property.
     *
     * @return flight number.
     */
    public long getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     *
     * @param value new flight number.
     */
    public void setNumber(long value) {
        this.number = value;
    }

    /**
     * Gets the value of the aircraft property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAircraft() {
        return aircraft;
    }

    /**
     * Sets the value of the aircraft property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAircraft(String value) {
        this.aircraft = value;
    }

    /**
     * Gets the value of the flightId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFlightId() {
        return flightId;
    }

    /**
     * Sets the value of the flightId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFlightId(String value) {
        this.flightId = value;
    }

    @Override
    public String toString() {
        return (new Formatter()).format(
                "{\"flightId\":\"%s\",\"company\":\"%s\",\"number\":%d,\"aircraft\":\"%s\"}",
                this.flightId, this.company, this.number, this.aircraft).toString();
    }
}
