<?xml version="1.0" encoding="UTF-8" ?>
<!--
    Copyright (c) 2026 Contributors to the Eclipse Foundation.
    Copyright (c) 2022, 2024 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-tck</artifactId>
    <version>4.0.0</version>
    <packaging>jar</packaging>

    <name>Jakarta RESTful WS Compliance for Jersey</name>
    <description>This test verifies the compliance of Eclipse Jersey with Jakarta REST</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jersey.version>4.0.99-SNAPSHOT</jersey.version> <!-- the public version that pass the tck -->
        <glassfish.version>8.0.4</glassfish.version>
        <glassfish.home>${project.build.directory}/glassfish8</glassfish.home>
        <jakarta.platform.version>10.0.0</jakarta.platform.version>
        <junit.jupiter.version>5.7.2</junit.jupiter.version>
        <jakarta.rest.version>4.0.0</jakarta.rest.version>
        <tck.artifactId>jakarta-restful-ws-tck</tck.artifactId>
        <tck.version>4.0.1</tck.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.jupiter.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jersey</groupId>
                <artifactId>jersey-bom</artifactId>
                <version>${jersey.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta-restful-ws-tck</artifactId>
            <version>${tck.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>ee.omnifish.arquillian</groupId>
            <artifactId>glassfish-client-ee11</artifactId>
            <version>2.2.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ee.omnifish.arquillian</groupId>
            <artifactId>arquillian-glassfish-server-managed</artifactId>
            <version>2.2.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.junit5</groupId>
            <artifactId>arquillian-junit5-container</artifactId>
            <version>1.10.2.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>sigtest-maven-plugin</artifactId>
            <version>2.7</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-httpclient</groupId>
            <artifactId>commons-httpclient</artifactId>
            <version>3.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>3.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- For SE TCK tests -->
        <dependency>
            <groupId>org.glassfish.jersey.containers</groupId>
            <artifactId>jersey-container-grizzly2-http</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.11.0</version>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>org.glassfish.main.distributions</groupId>
                                    <artifactId>glassfish</artifactId>
                                    <version>${glassfish.version}</version>
                                    <type>zip</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <stripVersion>true</stripVersion>
                            <stripClassifier>true</stripClassifier>
                            <outputDirectory>${glassfish.home}/glassfish/modules</outputDirectory>
                            <overWriteReleases>true</overWriteReleases>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.containers</groupId>
                                    <artifactId>jersey-container-grizzly2-http</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.containers</groupId>
                                    <artifactId>jersey-container-servlet</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>

                                <artifactItem>
                                    <groupId>org.glassfish.jersey.core</groupId>
                                    <artifactId>jersey-client</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.core</groupId>
                                    <artifactId>jersey-common</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.core</groupId>
                                    <artifactId>jersey-server</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>

                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext</groupId>
                                    <artifactId>jersey-bean-validation</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext</groupId>
                                    <artifactId>jersey-entity-filtering</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext</groupId>
                                    <artifactId>jersey-mvc</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext</groupId>
                                    <artifactId>jersey-mvc-jsp</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext.cdi</groupId>
                                    <artifactId>jersey-cdi1x</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext.cdi</groupId>
                                    <artifactId>jersey-cdi1x-servlet</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext.cdi</groupId>
                                    <artifactId>jersey-cdi1x-transaction</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext.cdi</groupId>
                                    <artifactId>jersey-cdi-rs-inject</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.ext.microprofile</groupId>
                                    <artifactId>jersey-mp-rest-client</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>

                                <artifactItem>
                                    <groupId>org.glassfish.jersey.inject</groupId>
                                    <artifactId>jersey-hk2</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>

                                <artifactItem>
                                    <groupId>org.glassfish.jersey.media</groupId>
                                    <artifactId>jersey-media-jaxb</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.media</groupId>
                                    <artifactId>jersey-media-json-binding</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.media</groupId>
                                    <artifactId>jersey-media-json-jackson</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.media</groupId>
                                    <artifactId>jersey-media-json-jettison</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.media</groupId>
                                    <artifactId>jersey-media-json-processing</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.media</groupId>
                                    <artifactId>jersey-media-multipart</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jersey.media</groupId>
                                    <artifactId>jersey-media-sse</artifactId>
                                    <version>${jersey.version}</version>
                                </artifactItem>

                                <artifactItem>
                                    <groupId>jakarta.ws.rs</groupId>
                                    <artifactId>jakarta.ws.rs-api</artifactId>
                                    <version>${jakarta.rest.version}</version>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.5.6</version>
                <executions>
                    <execution>
                        <id>gf-tests</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <exclude>**/SeBootstrapIT.java</exclude>
                            </excludes>
                            <test>${run.test}</test>
                            <skipTests>false</skipTests>
                            <dependenciesToScan>jakarta.ws.rs:${tck.artifactId}</dependenciesToScan>
                            <systemPropertyVariables>
                                <glassfish.home>${glassfish.home}</glassfish.home>

                                <glassfish.postBootCommands>
                                    --passwordfile ${basedir}/j2ee.pass create-file-user --groups staff:mgr:DIRECTOR j2ee
                                    --passwordfile ${basedir}/javajoe.pass create-file-user --groups guest:OTHERROLE javajoe
                                    set server-config.network-config.protocols.protocol.http-listener-1.http.trace-enabled=true
                                </glassfish.postBootCommands>

                                <user>j2ee</user>
                                <password>j2ee</password>
                                <authuser>javajoe</authuser>
                                <authpassword>javajoe</authpassword>

                                <webServerHost>localhost</webServerHost>
                                <webServerPort>8080</webServerPort>

                                <servlet_adaptor>org.glassfish.jersey.servlet.ServletContainer</servlet_adaptor>
                                <junit.log.traceflag>true</junit.log.traceflag>
                                <porting.ts.url.class.1>ee.jakarta.tck.ws.rs.lib.implementation.sun.common.SunRIURL</porting.ts.url.class.1>
                                <jimage.dir>${project.build.directory}/jdk-bundle</jimage.dir>
                                <optional.tech.packages.to.ignore>jakarta.xml.bind</optional.tech.packages.to.ignore>
                                <signature.sigTestClasspath>${glassfish.home}/glassfish/modules/jakarta.ws.rs-api.jar:${glassfish.home}/glassfish/modules/jakarta.xml.bind-api.jar:${project.build.directory}/jdk-bundle/java.base:${project.build.directory}/jdk-bundle/java.rmi:${project.build.directory}/jdk-bundle/java.sql:${project.build.directory}/jdk-bundle/java.naming</signature.sigTestClasspath>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>
                    <execution>
                        <id>se-tests</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <skipTests>false</skipTests>
                            <includes>
                                <include>**/SeBootstrapIT.java</include>
                            </includes>
                            <dependenciesToScan>jakarta.ws.rs:${tck.artifactId}</dependenciesToScan>
                        </configuration>
                    </execution>
                    <execution>
                        <id>verify-tests</id>
                        <goals>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>onLinux</id>
            <activation>
                <os>
                    <family>unix</family>
                </os>
            </activation>
            <properties>
                <asadmin.home>${basedir}</asadmin.home>
                <asadmin>${glassfish.home}/glassfish/bin/asadmin</asadmin>
            </properties>
        </profile>
        <profile>
            <id>onWindows</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <properties>
                <asadmin.home>${glassfish.home}/glassfish/bin</asadmin.home>
                <asadmin>asadmin</asadmin>
            </properties>
        </profile>
    </profiles>
</project>
